# Registration
REGISTER_NAME: int = 1
REGISTER_PHONE: int = 2
REGISTER_LICENSE: int = 3
REGISTER_LICENSE_PHOTO: int = 4

# Targets
DAILY_TARGET_TYPE: int = 5
DAILY_TARGET_VALUE: int = 6

# Start Trip
START_TRIP_VEHICLE: int = 7
START_TRIP_DEST: int = 8
START_TRIP_ODO: int = 9
START_TRIP_IMAGE: int = 10
START_TRIP_LOC: int = 11

# End Trip
END_TRIP_VEHICLE: int = 12
END_TRIP_ODO: int = 13
END_TRIP_IMAGE: int = 14
END_TRIP_LOC: int = 15

# Fuel & Finance
FUEL_PROMPT: int = 16
FUEL_DATA: int = 17
FUEL_IMAGE: int = 18
END_TRIP_REVENUE: int = 19
END_TRIP_OTHER_EXP: int = 20
END_TRIP_EXPENSE_PHOTO: int = 21
END_TRIP_SUMMARY: int = 22

# Incidents
REPORT_VEHICLE: int = 23
REPORT_DESC: int = 24
REPORT_PHOTO: int = 25

# Admin
ADMIN_DL_FROM: int = 26
ADMIN_DL_TO: int = 27
ADMIN_BROADCAST: int = 28
